name: TopGUI
options:
  bundleIdPrefix: com.jordankoch
  deploymentTarget:
    macOS: "13.0"
  developmentLanguage: en

targets:
  TopGUI:
    type: application
    platform: macOS
    sources:
      - TopGUI
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jordankoch.TopGUI
        INFOPLIST_FILE: TopGUI/Info.plist
        PRODUCT_NAME: TopGUI
        SWIFT_VERSION: "5.0"
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        CURRENT_PROJECT_VERSION: "2"
        MARKETING_VERSION: "2.0.0"
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_ENTITLEMENTS: TopGUI/TopGUI.entitlements
    entitlements:
      path: TopGUI/TopGUI.entitlements
